# Generated by Django 6.0.2 on 2026-02-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_bruto', models.DecimalField(decimal_places=2, default=13812.0, max_digits=12, verbose_name='Volume Bruto ($)')),
                ('novos_clientes', models.IntegerField(default=45, verbose_name='Novos Clientes')),
                ('pagamentos_realizados', models.IntegerField(default=120, verbose_name='Pagamentos Realizados')),
                ('volume_liquido', models.DecimalField(decimal_places=2, default=9000.0, max_digits=12, verbose_name='Volume Líquido ($)')),
            ],
            options={
                'verbose_name': 'Métrica do Dropdown',
                'verbose_name_plural': 'Métricas do Dropdown',
            },
        ),
    ]
