# Generated by Django 6.0.2 on 2026-02-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardmetrics',
            name='novos_clientes_ontem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboardmetrics',
            name='pagamentos_realizados_ontem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboardmetrics',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dashboardmetrics',
            name='volume_bruto_ontem',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dashboardmetrics',
            name='volume_liquido_ontem',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dashboardmetrics',
            name='novos_clientes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dashboardmetrics',
            name='pagamentos_realizados',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dashboardmetrics',
            name='volume_bruto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dashboardmetrics',
            name='volume_liquido',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
