# Generated by Django 6.0.2 on 2026-02-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dashboardmetrics_novos_clientes_ontem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardmetrics',
            name='repasses',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dashboardmetrics',
            name='saldo_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
