# Generated by Django 6.0.2 on 2026-02-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dashboardmetrics_repasses_dashboardmetrics_saldo_usd'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldosMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('entrada', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('disponivel', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Métrica de Saldos',
                'verbose_name_plural': 'Métricas de Saldos',
            },
        ),
    ]
