# Generated by Django 6.0.2 on 2026-02-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_saldosmetrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='saldosmetrics',
            name='atividade_1_data',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='saldosmetrics',
            name='atividade_1_valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saldosmetrics',
            name='atividade_2_data',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='saldosmetrics',
            name='atividade_2_valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saldosmetrics',
            name='atividade_3_data',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='saldosmetrics',
            name='atividade_3_valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
