# Generated by Django 6.0.2 on 2026-02-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_saldosmetrics_atividade_1_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransacoesMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tudo', models.IntegerField(default=0)),
                ('ok', models.IntegerField(default=0)),
                ('reembolsados', models.IntegerField(default=0)),
                ('contestados', models.IntegerField(default=0)),
                ('malsucedidos', models.IntegerField(default=0)),
                ('nao_capturados', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Métrica de Transações',
                'verbose_name_plural': 'Métricas de Transações',
            },
        ),
    ]
