# Generated by Django 6.0.2 on 2026-02-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_transacoesmetrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacoesmetrics',
            name='valor1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transacoesmetrics',
            name='valor10',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transacoesmetrics',
            name='valor11',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transacoesmetrics',
            name='valor2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transacoesmetrics',
            name='valor3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transacoesmetrics',
            name='valor4',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transacoesmetrics',
            name='valor5',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transacoesmetrics',
            name='valor6',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transacoesmetrics',
            name='valor7',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transacoesmetrics',
            name='valor8',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transacoesmetrics',
            name='valor9',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
