# Generated by Django 6.0.2 on 2026-02-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_transacoesmetrics_valor1_transacoesmetrics_valor10_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientesMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome1', models.CharField(default='Minneapolis Mental Health', max_length=255)),
                ('nome2', models.CharField(default='San Diego Fertility Center', max_length=255)),
                ('nome3', models.CharField(default='Milwaukee Urology Specialists', max_length=255)),
                ('nome4', models.CharField(default='Virginia Rheumatology Clinic', max_length=255)),
                ('nome5', models.CharField(default='Radiology Partners', max_length=255)),
                ('nome6', models.CharField(default='Boston Heart Center', max_length=255)),
                ('nome7', models.CharField(default='Houston Methodist', max_length=255)),
                ('nome8', models.CharField(default='Mayo Clinic', max_length=255)),
                ('nome9', models.CharField(default='Cleveland Clinic', max_length=255)),
                ('nome10', models.CharField(default='New York Presbyterian', max_length=255)),
                ('nome11', models.CharField(default='UCLA Health', max_length=255)),
                ('nome12', models.CharField(default='Johns Hopkins Medicine', max_length=255)),
                ('email1', models.EmailField(default='support@minneapolismentalhealth.com', max_length=254)),
                ('email2', models.EmailField(default='info@sdfertility.com', max_length=254)),
                ('email3', models.EmailField(default='info@milwaukeeurology.com', max_length=254)),
                ('email4', models.EmailField(default='care@varheum.com', max_length=254)),
                ('email5', models.EmailField(default='scheduling@radpartnersnv.com', max_length=254)),
                ('email6', models.EmailField(default='finance@bostonheart.com', max_length=254)),
                ('email7', models.EmailField(default='support@houstonmethodist.org', max_length=254)),
                ('email8', models.EmailField(default='accounts@mayo.com', max_length=254)),
                ('email9', models.EmailField(default='contact@clevelandclinic.org', max_length=254)),
                ('email10', models.EmailField(default='info@nyp.org', max_length=254)),
                ('email11', models.EmailField(default='support@uclahealth.org', max_length=254)),
                ('email12', models.EmailField(default='patientcare@jhmi.edu', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Métrica de Clientes',
                'verbose_name_plural': 'Métricas de Clientes',
            },
        ),
    ]
