# Generated by Django 6.0.2 on 2026-02-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_clientesmetrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=1)),
                ('ativos', models.IntegerField(default=1)),
                ('arquivados', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Métrica de Catálogo',
                'verbose_name_plural': 'Métricas de Catálogo',
            },
        ),
    ]
