# Generated by Django 6.0.2 on 2026-02-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_catalogometrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogometrics',
            name='produto_data',
            field=models.CharField(default='10 de ago.', max_length=50),
        ),
        migrations.AddField(
            model_name='catalogometrics',
            name='produto_data_atualizado',
            field=models.CharField(default='5 de jan.', max_length=50),
        ),
        migrations.AddField(
            model_name='catalogometrics',
            name='produto_nome',
            field=models.CharField(default='Á CUPULA DIGITAL', max_length=255),
        ),
        migrations.AddField(
            model_name='catalogometrics',
            name='produto_preco',
            field=models.DecimalField(decimal_places=2, default=1890.79, max_digits=12),
        ),
    ]
