# Generated by Django 6.0.2 on 2026-02-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_catalogometrics_produto_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricasGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(choices=[('hoje', 'Hoje'), ('ultimos7dias', 'Últimos 7 dias'), ('ultimas4semanas', 'Últimas 4 semanas'), ('ultimos6meses', 'Últimos 6 meses'), ('ultimos12meses', 'Últimos 12 meses'), ('mesatedata', 'Meses até a data'), ('trimesteateadata', 'Trimestre até a data'), ('anoateadata', 'Ano até a data'), ('desdoinicio', 'Desde o início')], max_length=20, unique=True, verbose_name='Período')),
                ('valor_bruto', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Bruto')),
                ('volume_bruto_anterior', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Volume Bruto Anterior')),
                ('volume_liquido', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Volume Líquido')),
                ('volume_liquido_anterior', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Volume Líquido Anterior')),
                ('clientes', models.IntegerField(default=0, verbose_name='Clientes')),
                ('clientes_anterior', models.IntegerField(default=0, verbose_name='Clientes Anterior')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Métrica Geral (Dashboard)',
                'verbose_name_plural': 'Métricas Gerais (Dashboard)',
            },
        ),
    ]
