# Generated by Django 6.0.2 on 2026-02-27 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_metricasgeral'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardmetrics',
            options={'verbose_name': 'Métricas Hoje', 'verbose_name_plural': 'Métricas Hoje'},
        ),
    ]
