# Generated by Django 6.0.2 on 2026-02-27 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_dashboardmetrics_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metricasgeral',
            options={'verbose_name': 'Métrica Visão Geral', 'verbose_name_plural': 'Métricas Visão Geral'},
        ),
    ]
