# Generated by Django 6.0.4 on 2026-04-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_metricasgeral_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacoesmetrics',
            name='data1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='transacoesmetrics',
            name='data10',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='transacoesmetrics',
            name='data11',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='transacoesmetrics',
            name='data2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='transacoesmetrics',
            name='data3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='transacoesmetrics',
            name='data4',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='transacoesmetrics',
            name='data5',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='transacoesmetrics',
            name='data6',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='transacoesmetrics',
            name='data7',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='transacoesmetrics',
            name='data8',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='transacoesmetrics',
            name='data9',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='transacoesmetrics',
            name='nome1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transacoesmetrics',
            name='nome10',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transacoesmetrics',
            name='nome11',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transacoesmetrics',
            name='nome2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transacoesmetrics',
            name='nome3',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transacoesmetrics',
            name='nome4',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transacoesmetrics',
            name='nome5',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transacoesmetrics',
            name='nome6',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transacoesmetrics',
            name='nome7',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transacoesmetrics',
            name='nome8',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transacoesmetrics',
            name='nome9',
            field=models.CharField(default='', max_length=255),
        ),
    ]
